---
title: "HW2"
author: "Sachi Vyas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1a

regmodel <- lm(Gpa ~ Act, CH01PR19)
summary(regmodel)

#1b and c
confint(regmodel)

#1d
predict(regmodel, data.frame(Act=28), interval="confidence", level=0.95, se.fit=T)

#1e
predict(regmodel, data.frame(Act=28), interval="prediction", level=0.95, se.fit=TRUE)

#1g
2*(1-pt(3.040,118))
pt(3.040,118)
1-pt(3.040,118)

2*(1-pt(2.4408,118))
pt(2.4408,118)
1-pt(3.040,118)
```

```{r}
#2
CH01PR22 <- read.delim("C:/Users/sachi/OneDrive/Desktop/430 notes/datasets/CH01PR22.txt", sep = "", header = FALSE, col.names = c("Hardness", "Timelapse"))

#2a
model <- lm(Hardness ~ Timelapse, CH01PR22)
summary(model)
anova(model)
confint(model)

#2d
predict(model, data.frame(Timelapse=36), interval="confidence", level=0.95, se.fit=T)
predict(model, data.frame(Timelapse=43), interval="confidence", level=0.95, se.fit=T)

#2e
predict(model, data.frame(Timelapse=43), interval="prediction", level=0.95, se.fit=T)
```

```{r}
#3
pf(447.106,1,38)
```

```{r}
#4a
surg.data <- read.delim("C:/Users/sachi/OneDrive/Desktop/430 notes/datasets/CH09TA01.txt", sep = "",
header=FALSE,
col.names = c("clot", "PI", "enzy", "liver", "age",
"gender", "mod_use", "heavy_use", "sur_time",
"ln_sur_time"))
attach(surg.data)
gender=factor(gender)
surg.data1<- surg.data[ ,seq(1,4)] # new data set
survival_time <- lm(sur_time~clot)
summary(survival_time)

#4b and c
confint(survival_time)

#4d
predict(survival_time, data.frame(clot=7.5), interval="confidence", level=0.95, se.fit=T)

#4e
predict(survival_time, data.frame(clot=7.5), interval="prediction", level=0.95, se.fit=T)
```

